os: osx
osx_image: xcode10.3

stages:
  - Build

jobs:
  include:
    - stage: Build
      script: ./bin/build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "./dist/Alpaca.zip"
        skip_cleanup: true
        on:
          tags: true

